---
name: Docker Image CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  IMAGE_NAME: ghcr.io/iloveitaly/github-actions-metadata-sync

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # gh secret set GH_PERSONAL_TOKEN --app actions --body ghp_
          password: ${{ secrets.GH_PERSONAL_TOKEN }}

      - name: Set Docker tag
        id: date
        run: echo "DATE_STAMP=$(date +%s)" > "$GITHUB_ENV"

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.DATE_STAMP }}
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:v1
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
